hw/hw14/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('category/<str:slug>/', views.category_page),
    path('create_post/', views.PostCreate.as_view()),
    path('<int:pk>/', views.single_post_page, name='single_post_page'),
    path('', views.index, name='index'),
    path('blog_list', views.blog_list, name='blog_list'),
    path('about_me', views.about_me, name='about_me')
]

hw/hw14/hw14_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw/hw14/blog/models.py
from django.db import models
from django.contrib.auth.models import User
import os

class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return f'/blog/category/{self.slug}/'

    
    class Meta:
        verbose_name_plural = 'Categories'

class Post(models.Model):
    title = models.CharField(max_length=30)
    preview = models.CharField(max_length=50)
    content = models.TextField()

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    file_upload = models.FileField(upload_to='blog/files/%Y/%m/%d/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL)

    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'
    
    def get_absolute_url(self):
        return f'/blog/{self.pk}/'

hw/hw14/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Category

def index(request):
    return render(
        request,
        'blog/index.html',
        {
            'title': 'main'
        }
    )

def blog_list(request):
    posts = Post.objects.all().order_by('-pk')
    return render(
        request,
        'blog/blog_list.html',
        {
            'title': 'blog',
            'subtitle': '블로그',
            'posts': posts
        }
    )

def single_post_page(request, pk):
    post = Post.objects.get(pk=pk)
    return render(
        request,
        'blog/single_post_page.html',
        {
            'title': 'blog_detail',
            'subtitle': '블로그_상세',
            'post': post
        }
    )

def about_me(request):
    return render(
        request,
        'blog/about_me.html',
        {
            'title': 'about us',
            'subtitle': '어바웃 어스'
        }
    )

# def category_page(request, slug):
#     if slug == 'no_category':
#         category = '미분류'
#         post_list = Post.objects.filter(category=None)
#     else:
#         category = Category.objects.get(slug=slug)
#         post_list = Post.objects.filter(category=category)

#     return render(
#         request,
#         'blog/blog_list.html',
#         {
#         'post_list': post_list,
#         'categories': Category.objects.all(),
#         'no_category_post_count': Post.objects.filter(category=None).count(),
#         'category': category,
#         }
#     )


class PostCreate(CreateView):
    model = Post
    fields = ['title', 'preview', 'content', 'head_image', 'file_upload', 'category', 'tags']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect("/blog/")

hw/hw14/blog/templates/blog/about_me.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-lg-8">
                <article>
                    <header class="mb-4">
                        <h1 class="fw-bolder mb-1">저희에 대해</h1>
                        <a class="badge bg-secondary text-decoration-none link-light" href="https://www.jbnu.ac.kr">전북대학교</a>
                        <a class="badge bg-secondary text-decoration-none link-light" href="https://sfarm.jbnu.ac.kr/">스마트팜학과</a>
                    </header>
                    <figure class="mb-4"><iframe name="img" class="img-fluid rounded" style="display:block; width:100%; height: 100vh" src=""></iframe></figure>
                    <section class="mb-5">
                        <p class="fs-5 mb-4">안녕하세요! 저희는 스마트팜학과 21학번 김성은, 23학번 정서현입니다.</p>
                        <p class="fs-5 mb-4">취미는 <A HREF="{% static 'blog/image/music.jpg' %}" target="img">노래 감상</A>과 <A HREF="{% static 'blog/image/health.jpg' %}" target="img">헬스</A>입니다.</p>
                        <p class="fs-5 mb-4">앞으로 과제를 통해 성장해 나가는 모습을 보여드리겠습니다.</p>
                    </section>
                </article>
            </div>
        </div>
    </div>
{% endblock %}

hw/hw14/blog/templates/blog/blog_list.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    <header class="py-5 bg-light border-bottom mb-4">
        <div class="container">
            <div class="text-center my-5">
                <h1 class="fw-bolder">블로그 홈</h1>
                {% if posts|length > 0 %}
                <p class="lead mb-0">게시물은 최신순으로 정렬됩니다.</p>
                {% else %}
                <p class="lead mb-0">게시물이 없습니다.</p>
                {% endif %}
            </div>
        </div>
    </header>
<!--
    <h1>{% if category %}<span class="badge badge-secondary">{{ category }}</span>{% endif %}</h1>
    <div class="card my-4" id="categories-card">
        <h5 class="card-header">카테고리</h5>
        <div class="card-body">
            <div class="row">
                <ul class="list-unstyled mb-0">
                {% for category in categories %}
                    <li>
                        <a href="{{ category.get_absolute_url }}">{{ category }} ({{category.post_set.count }})</a>
                    </li>
                {% endfor %}
                    <li>
                        <a href="/blog/category/no_category/">미분류 ({{ no_category_post_count }})</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
-->
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row">
                    <a class="btn btn-info btn-sm float-right" href="/blog/create_post" role="button"><i class="fas fa-pen">New Post</i></a>
                    <div class="col-lg-6">
                        {% for post in posts %}
                        <div class="card mb-4" id="post-{{ post.pk }}">
                            <a href="#!">{% if post.head_image %}<img class="card-img-top" src="{{ post.head_image.url }}" alt="Card image cap" />{% endif %}</a>
                            <div class="card-body">
                                <div class="small text-muted">Posted on {{ post.created_at}} by {{ post.author | upper }}</div>
                                <span class="badge badge-secondary float-right">{{ post.category }}</span>
                                <h2 class="card-title h4">{{ post.title }}</h2>
                                <p class="card-text">{{ post.preview }}</p>
                                {% if post.tags.exists %}
                                    <i class="fas fa-tags"></i>Tag : 
                                    {% for tag in post.tags.iterator %}
                                        <a href="#"><span class="badge badge-secondary" style="color: black;">{{ tag }}</span></a>
                                    {% endfor %}
                                    <br>
                                {% endif %}
                                <a class="btn btn-primary" href="{{ post.get_absolute_url }}">본문으로</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

hw/hw14/blog/templates/blog/index.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
<header class="py-5 bg-light border-bottom mb-4">
    <div class="container">
        <div class="text-center my-5">
            <h1 class="fw-bolder">응소 10조의 홈페이지에 오신 것을 환영합니다!</h1>
            <p class="lead mb-0">여기는 저희의 홈페이지입니다. 다양한 주제에 대해 블로그 글을 올리고, 저희에 대해 더 알아볼 수 있습니다.</p>
        </div>
        <a class="btn btn-primary" href="https://github.com/lifelo/softeng2024_together">조별과제 업로드 깃허브</a>
    </div>
</header>
{% endblock %}

hw/hw14/blog/templates/blog/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    {% if title %}
    <title>Team Homepage - {{ title }}</title>
    {% else %}
    <title>Team Homepage</title>
    {% endif %}
    <link rel="icon" type="image/x-icon" href="{% static 'blog/assets/favicon.ico' %}" />
    <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            {% if subtitle %}
            <a class="navbar-brand" href="#!">과제12 웹사이트 만들기 - {{ subtitle }}</a>
            {% else %}
            <a class="navbar-brand" href="#!">과제12 웹사이트 만들기</a>
            {% endif %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'blog:about_me' %}">About Us</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'blog:blog_list' %}">Blog</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <main role="main">
    {% block content %}{% endblock %}
    </main>
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Our Website 2024</p>
            <p id="clock" class="m-0 text-center text-white"></p>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'blog/js/source.js' %}"></script>
</body>
</html>

hw/hw14/blog/templates/blog/post_form.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    <h1>Create New Post</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>
            {{ form }}
        </table>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>

{% endblock %}

hw/hw14/blog/templates/blog/single_post_page.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{ post.title }}
                    {% if post.category %}
                     - {{ post.category }}
                    {% else %}
                     - 미분류
                    {% endif %}
                    </h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">{{ post.created_at}} by {{ post.author | upper }}</div>
                    {% if post.tags.exists %}
                        <i class="fas fa-tags"></i>Tag : 
                        {% for tag in post.tags.iterator %}
                            <a href="#"><span class="badge badge-secondary" style="color: black;">{{ tag }}({{ tag.post_set.count}})</span></a>
                        {% endfor %}
                    {% endif %}
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4">{% if post.head_image %}<img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="" />{% endif %}</figure>
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{ post.content }}</p>
                </section>
            </article>
        </div>
    </div>
{% endblock %}