hw/hw09/hw09_prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('single_pages.urls')),
]

hw/hw09/single_pages/urls.py
from django.urls import path
from . import views

app_name = "single_pages"

urlpatterns = [
    path('blog_list/', views.blog_list, name='blog_list'),
    path('about_me/', views.about_me, name='about_me'),
    path('', views.landing, name='landing'),
]

hw/hw09/single_pages/views.py
from django.shortcuts import render
import json

# Create your views here.
def landing(request):
    return render(
        request,
        'single_pages/landing.html'
    )

def about_me(request):
    return render(
        request,
        'single_pages/about_me.html', 
        {'title': 'About_me', 'subtitle': '어바웃_미'}
    )

def blog_list(request):
    with open('./blog.json', 'r', encoding='utf-8') as f:
        blog = json.load(f)
    return render(
        request,
        'single_pages/blog_list.html', 
        {'title': 'Blog', 'subtitle': '블로그', 'posts': blog}
    )

hw/hw09/single_pages/templates/single_pages/about_me.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    <section width="100%">
        <h2>저희에 대해</h2>
        <p>안녕하세요! 저희는 스마트팜학과 21학번 김성은, 23학번 정서현입니다.</p>
        <p>취미는 <A HREF="{% static 'single_pages/image/music.jpg' %}" target="img">노래 감상</A>과 <A HREF="{% static 'single_pages/image/health.jpg' %}" target="img">헬스</A>입니다. 앞으로 과제를 통해 성장해 나가는 모습을 보여드리겠습니다.</p>
        <h3>저희의 취미</h3>
        <figure>
            <iframe src="" name="img" style="display:block; width:100%; height: 100vh"> </iframe>
        </figure>
    </section>
{% endblock %}

hw/hw09/single_pages/templates/single_pages/blog_list.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
{% if posts|length > 0 %}
{% for post in posts %}
    <section>
    <h2>
    {% if post.url %}
    <a href="{{ post.url }}">{{ post.title }}</a>
    {% else %}
    {{ post.title }}
    {% endif %}
    </h2>
    <ul>
        <li>
            {{ post.content }}
        </li>
    </ul>
    </section>
    <br>
{% endfor %}
{% else %}
    <p>내용 없음</p>
{% endif %}
{% endblock %}

hw/hw09/single_pages/templates/single_pages/landing.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
<section>
    <h2>응소 10조의 홈페이지에 오신 것을 환영합니다.</h2>
    <p>여기는 저희의 홈페이지입니다. 다양한 주제에 대해 블로그 글을 올리고, 저희에 대해 더 알아볼 수 있습니다.</p>
    <a href="https://github.com/lifelo/softeng2024_together">조별과제 업로드 깃허브</a><br><br>
</section>
{% endblock %}

hw/hw09/single_pages/templates/single_pages/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
    <title>Team Homepage - {{ title }}</title>
    {% else %}
    <title>Team Homepage</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'single_pages/layout.css' %}">
    <style>
        h1 { color: black; background-color: yellow; transition: color background-color 1s;}
        h1:hover {color: yellow; background-color: black;}
    </style>
</head>
<body>
    <header>
        <div id="clock"></div>
        <script src="{% static 'single_pages/source.js' %}"></script>
        {% if subtitle %}
        <h1>과제06 웹사이트 만들기 - {{ subtitle }}</h1>
        {% else %}
        <h1>과제06 웹사이트 만들기</h1>
        {% endif %}
    </header>
    <nav>
        <a href="{% url 'single_pages:landing' %}">Home</a>
        <a href="{% url 'single_pages:blog_list' %}">Blog</a>
        <a href="{% url 'single_pages:about_me' %}">About Us</a>
    </nav>
    <hr>

    <main role="main">
    {% block content %}{% endblock %}
    </main>
</body>
</html>